# День 10 – Введение в анализ данных

В этом проекте мы поможем вам приобрести навыки работы с библиотекой Pandas. Она является основой для работы с датафреймами. Название этой библиотеки происходит от термина «панельные данные» (panel data), экономико-математического термина для наборов данных, которые включают наблюдения за несколько периодов времени для одних и тех же компаний или людей.

## 0. Импорт библиотек

In [6]:
import pandas as pd

## 1. Task 1 загрузка и сохранение

В этом упражнении вам нужно загрузить файл журнала и поместить его в подкаталог data в корневом каталоге, который вы используете в рамках этого упражнения. Затем загрузить его в датафрейм, изменить разделитель и сохранить получившийся результат в другой файл.
Ваши задачи в рамках этого упражнения в деталях.
1.	Используя метод read_csv:
*   отфильтруйте строки с индексами 2 и 3 с помощью аргумента skiprows (мы заведомо знаем, что эти наблюдения были фиктивными);
*   отфильтруйте последние 2 строки таблицы с помощью аргумента skipfooter (мы знаем, что эти наблюдения тоже были фиктивными);
*   присвойте столбцам следующие имена: datetime, user;
используйте datetime в качестве столбца индекса.

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
df = pd.read_csv('../content/drive/MyDrive/School21/Day10/data/feed-views.log',
                 sep='\t',
                 engine='python',
                 header=None,
                 skiprows=[2, 3],
                 skipfooter=2,
                 names = ['datetime', 'user'],
                 index_col = 'datetime'
                 )
df

                                 user
datetime
2020-04-17 12:01:08.463179      artem
2020-04-17 12:01:23.743946      artem
2020-04-17 12:35:52.735016      artem
2020-04-17 12:36:21.401412     oksana
2020-04-17 12:36:22.023355     oksana
...                               ...
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

[1072 rows x 1 columns]

2.	Переименуйте datetime в date_time.

In [9]:
df.index.names = ['date_time'];df

                                 user
date_time
2020-04-17 12:01:08.463179      artem
2020-04-17 12:01:23.743946      artem
2020-04-17 12:35:52.735016      artem
2020-04-17 12:36:21.401412     oksana
2020-04-17 12:36:22.023355     oksana
...                               ...
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

[1072 rows x 1 columns]

3.	Используя метод to_csv:
*   используйте ; в качестве разделителя;
*   сохраните данные в файл с именем feed-views-semicolon.log.

In [11]:
df.to_csv('../content/drive/MyDrive/School21/Day10/task1/feed-views-semicolon.log', sep=';')